### ISSUE TITLE
Clickable "API Playground" link on the front page

### ISSUE THREAD

**Issue by OlegIlyenko** [sphereio/sphere-express-impex#46]
It would be nice to make this section of the page clickable:

![sphere_io _-_express_impex_gui](https://cloud.githubusercontent.com/assets/156569/6286970/9e60b01c-b90d-11e4-958b-480a37677a3d.png)

**Comment by butenkor** [comment]
I was tricked too :)

**Comment by svenmueller** [comment]
+1 for better UX

**Comment by hajoeichler** [comment]
:cry: why not?

**Comment by emmenko** [comment]
I find it completely inconsistent with the other sections. Either all are links or not, otherwise it's even more confusing. And the link is right there in the top navigation.

**Comment by nkuehn** [comment]
+1, I had the same issue for the first few times I used impex.

@emmenko  yes, the issue is not that the specific thing is not clickable (would just make things worse and inconsistent) but that the whole grid of elements looks too much like calls to action and that the menu is very softly designed in comparison.  Sorry,but the whole design is flawed somehow.

**Comment by OlegIlyenko** [comment]
:crying_cat_face:

**Comment by emmenko** [comment]
Actually I got the idea from our own website:

![screen shot 2015-06-02 at 21 24 40](https://cloud.githubusercontent.com/assets/1110551/7944913/d9506edc-096d-11e5-9276-c8dd74b71e7e.png)

What do you say about that? ;)

---

But if you think it's a crucial feature to have a link there I will put it there.

**Comment by hajoeichler** [comment]
@emmenko you are right - either no links or all need links. And we don't have useful links for all the 6 topics.
